/tv2x_bridge:
  ros__parameters:
    general:
      v2x_interface: "wlan1"
      asn_file_cam: "/home/mmr/aces/TruckV2X/src/tv2x_bridge/its_cam.asn"
      asn_file_denm: "/home/mmr/aces/TruckV2X/src/tv2x_bridge/its_denm.asn"
    topic:
      cam: "/v2x/cam"
      denm: "/v2x/denm"
      cam: "/v2x/gps_speed"
      denm: "/v2x/nav_sat_heading"